// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/articles": {
    params: {};
  };
  "/articles/:slug": {
    params: {
      "slug": string;
    };
  };
  "/about": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/uses": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/articles" | "/articles/:slug" | "/about" | "/projects" | "/uses";
  };
  "./layouts/main.tsx": {
    id: "layouts/main";
    page: "/" | "/articles" | "/articles/:slug" | "/about" | "/projects" | "/uses";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/articles.tsx": {
    id: "routes/articles";
    page: "/articles";
  };
  "./routes/article.tsx": {
    id: "routes/article";
    page: "/articles/:slug";
  };
  "./routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "./routes/uses.tsx": {
    id: "routes/uses";
    page: "/uses";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "layouts/main": typeof import("./src/./layouts/main.tsx");
  "routes/home": typeof import("./src/./routes/home.tsx");
  "routes/articles": typeof import("./src/./routes/articles.tsx");
  "routes/article": typeof import("./src/./routes/article.tsx");
  "routes/about": typeof import("./src/./routes/about.tsx");
  "routes/projects": typeof import("./src/./routes/projects.tsx");
  "routes/uses": typeof import("./src/./routes/uses.tsx");
};